### ISSUE TITLE
Update the contents of the website

### ISSUE THREAD

**Issue by gopalgoel19** [gopalgoel19/gopalgoel19.github.io#1]
Use this [profile](https://www.linkedin.com/in/gopalgoel19/) for details of the person.

**Comment by amrs-tech** [comment]
I'd like to take up this task :)

**Comment by 94151** [comment]
@gopalgoel19 please check my pull request.

**Comment by gopalgoel19** [comment]
> I'd like to take up this task :)

@amrs-tech Maybe you can work on updating the side panel and the About Me section. That is yet to be done.
