### ISSUE TITLE
Remove the unnecessary network calls that are being made in the website.

### ISSUE THREAD

**Issue by gopalgoel19** [gopalgoel19/gopalgoel19.github.io#10]
Improve ALT by removing unnecessary network calls and also apply other optimizations possible.

**Comment by echavezNS** [comment]
I'll check what can I do

**Comment by gopalgoel19** [comment]
![screenshot 48](https://user-images.githubusercontent.com/11490517/46463290-3674e680-c7e1-11e8-97c4-8a0e6bcbb460.png)

**Comment by echavezNS** [comment]
https://github.com/gopalgoel19/gopalgoel19.github.io/pull/22 was made
