### ISSUE TITLE
Update skills section

### ISSUE THREAD

**Issue by gopalgoel19** [gopalgoel19/gopalgoel19.github.io#12]
The updated data needs to be:
JavaScript: 80%
TypeScript: 70%
React: 70%
GraphQL: 40%
Git: 90%
CSS: 60%
C++: 80%

**Comment by mstruebing** [comment]
I'll do it

**Comment by gopalgoel19** [comment]
The skills need to be in the same order as the skills mentioned in the above comment.

**Comment by mstruebing** [comment]
fixed.
