### ISSUE TITLE
Change the content to third-person singular

### ISSUE THREAD

**Issue by gopalgoel19** [gopalgoel19/gopalgoel19.github.io#9]
[https://en.wiktionary.org/wiki/third-person_singular](https://en.wiktionary.org/wiki/third-person_singular)

**Comment by DevMasterAryan** [comment]
Which part is need to change according to third person singular.

**Comment by gopalgoel19** [comment]
Entire content. Eg. About me, experience, etc.

**Comment by AbidemiT** [comment]
Done
